apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000 # node ID
        runAsUser: 1000 # node ID
        runAsGroup: 1000 # node ID
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.32.1
          envFrom:
            - configMapRef:
                name: audiobookshelf-config
          ports:
            - containerPort: 3005
              protocol: TCP
          securityContext:
            allowPrivilegesEscalation: false
          volumeMounts:
            - name: audiobookshelf-audiobooks
              mountPath: /audiobooks
            - name: audiobookshelf-podcasts
              mountPath: /podcasts
            - name: audiobookshelf-config
              mountPath: /config
            - name: audiobookshelf-metadata
              mountPath: /metadata
      volumes:
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks
        - name: audiobookshelf-podcasts
          persistentVolumeClaim:
            claimName: audiobookshelf-podcasts
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata

